### ISSUE TITLE
Is it possible to update analyzer dependency?

### ISSUE THREAD

**Issue by makstheimba** [kawa1214/import-lint#16]
Very interesting package but we cannot use it due to outdated dependencies. Can you update please? 🙏

**Comment by kawa1214** [comment]
@makstheimba 

Thanks for the issue. I will update next week.

**Comment by kawa1214** [comment]
@makstheimba 
Thanks for issue.I've published version 0.9.4.

https://pub.dev/packages/import_lint/versions/0.9.4
