### ISSUE TITLE
merge fork

### ISSUE THREAD

**Issue by dominicmh** [kawa1214/import-lint#19]
Hi and thanks for this linter, it's very valuable to us!

Unfortunately, we had to switch to the [fork of this repo](https://github.com/lfariaUnifei/import-lint) in order to also restrict imports of external dependencies.

Are there any plans or intentions to merge this fork at some point? It introduces a few [fixes and features](https://github.com/kawa1214/import-lint/compare/main...lfariaUnifei:import-lint:main).

Thanks!

**Comment by kawa1214** [comment]
@dominicmh 
Thanks for the issue.

I saw the fork repository.
I would like to merge if possible. And the README and code have been updated and are very cool.

However, the version of the Analyzer plugin seems to be low.We need to Migration to analyzer 5.x.

I ask the owner of the forked repository.

**Comment by dominicmh** [comment]
@kawa1214
There were [recent updates](https://github.com/lfariaUnifei/import-lint/blob/main/pubspec.yaml) to the fork where the analyzer dependencies were upgraded:
```yaml
analyzer: ">=5.1.0 <5.5.0"
analyzer_plugin: ">=0.11.0 <0.12.0"
```
Does that update facilitate the merge of the fork?

**Comment by kawa1214** [comment]
Sorry, I need to add more tests and need more time.
I don't have time......
