### ISSUE TITLE
dart:* imports

### ISSUE THREAD

**Issue by dominicmh** [kawa1214/import-lint#25]
There's a slightly different behaviour when you try to apply the `exclude_imports` rules to `dart:*` imports, e.g. `import 'dart:io';`.
`exclude_imports: [ 'dart:io']` would be ignored and the linter will complain for such imports.
Instead, you need drop the "dart:" part, i.e. `exclude_imports: [ 'io']`.

I don't know how complicated it is to change the plugin to the expected behaviour. A quick fix would be to just add a note regarding `dart:` imports to the `README.md`.

**Comment by kawa1214** [comment]
@dominicmh 
thanks for the issue!
I will add it to the README.
