### ISSUE TITLE
Add an 'allow_imports' rule, as opposed to the 'not_allow_imports' rule

### ISSUE THREAD

**Issue by hbock-42** [kawa1214/import-lint#31]
Hello,

I feel like an 'allow_imports' rule would benefit this package.
Lets say I want to quickly define rules to enforce my architecture, it has more sense to says:
- application_rule:
      target_file_path: "application/**/*.dart"
      allow_imports: ["domain/**/*.dart"]
than:
-application_rule:
      target_file_path: "application/**/*.dart"
      not_allow_imports: ["infrastructure/**/*.dart", "main/**/*.dart", "presentation/**/*.dart"]

With the later, if a user add a file at the root of the lib folder, he can then use it inside the application folder. If the user creates a new folder, he can import files from this folder from the application folder.
With the former, we define once the where the files can come from, and it is done.

**Comment by kawa1214** [comment]
@hbock-42 
Thank you for the issue.

I have received similar suggestions from others, and I agree with them.
I am considering whether to maintain compatibility and how to do so.

**Comment by hbock-42** [comment]
@kawa1214  Thank you for the quick answer. Let me know if you have several implementations idea and would appreciate an outside opinion.
