### ISSUE TITLE
analysis_options.yaml in the parent directory could not be loaded

### ISSUE THREAD

**Issue by mj-hd** [kawa1214/import-lint#5]
The plugin failed to start by following error:
```
Failed to load options:: Exception:: Not found import_analysis_options.yaml file at the root of your project.
 FileSystemException:: Cannot open file, path = '/Users/mjhd/Projects/project_root/packages/package1/analysis_options.yaml' (OS Error:: No such file or directory, errno = 2)

#0 new Rules.fromOptionsFile (package::import_lint/src/import_lint_options.dart::58::7)
#1     new ImportLintOptions.init
```

CLI also fails to start by the same error.

My project structure looks like:
```
- Project Root
  - analysis_options.yaml
  - packages/
    - package1/ (current context root)
      - lib/...
      - pubspec.yaml
    - package2/
      - lib/...
      - pubspec.yaml
```

---

Dart Analyzer can read an options file in a parent directory of the target package's root.

> If the analyzer can’t find an analysis options file at the package root, it walks up the directory tree, looking for one. If no file is available, the analyzer defaults to standard checks.

https://dart.dev/guides/language/analysis-options#the-analysis-options-file

To support this behavior, `context?.contextRoot.optionsFile` should be used to load the options file.

similar code in `dart-code-metrics`: https://github.com/dart-code-checker/dart-code-metrics/blob/7d8269b420d7b40562b72149f92949b288cf40f1/lib/src/analyzer_plugin/analyzer_plugin.dart#L236

---

Thank you for creating this useful package, I will use this in my project!

**Comment by kawa1214** [comment]
@mj-hd 
Thak you for the error report and solution!

I understand the analysis options file specification.
I will fix this error.
