### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by kaboc** [kawa1214/import-lint#8]
I tried using this in my personal project, but no warning was printed in the Dart Analysis pane on the IDE (IntelliJ IDEA Ultimate) and `dart run import_lint` only showed "No issues found!".

I thought my settings might be wrong, so downloaded the code from this repository, but the example contained in it showed the same result.

**Environment**

> \> dart --version
> Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64"

**Comment by kawa1214** [comment]
Thank you for the report!

I will Inspect on the Windows machine.
